# Generated by Django 3.2.23 on 2023-11-07 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purityapp', '0002_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=70)),
                ('phone', models.IntegerField(default=0)),
                ('date', models.DateTimeField()),
                ('department', models.CharField(max_length=70)),
                ('doctor', models.CharField(max_length=70)),
                ('message', models.TextField()),
            ],
        ),
    ]
