# Generated by Django 3.2.23 on 2023-11-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purityapp', '0003_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='color',
            field=models.CharField(default='white', max_length=70),
        ),
        migrations.AddField(
            model_name='products',
            name='origin',
            field=models.CharField(default='Kenya', max_length=70),
        ),
    ]
