# Generated by Django 3.2.23 on 2023-11-12 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purityapp', '0004_auto_20231109_0857'),
    ]

    operations = [
        migrations.CreateModel(
            name='EggOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('delivery_date', models.DateField()),
            ],
        ),
    ]
