# Generated by Django 3.2.23 on 2023-11-12 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purityapp', '0006_auto_20231113_0148'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EggOrder',
            new_name='OrderEgg',
        ),
    ]
