# Generated by Django 3.2.23 on 2023-11-14 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purityapp', '0007_rename_eggorder_orderegg'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderEgg',
            new_name='Ordered',
        ),
    ]
