# Generated by Django 3.2.23 on 2023-11-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purityapp', '0009_alter_ordered_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('title', models.CharField(max_length=70)),
                ('price', models.CharField(max_length=70)),
            ],
        ),
    ]
